{% set name = "skope-rules" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/scikit-learn-contrib/skope-rules/archive/v{{ version }}.tar.gz
  sha256: af3ee6db100d59aad3da651b6dfa9adb5ad217d72e6b554180a87e2d8cdf3616

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.10
    - pip
    - setuptools 
  run:
    - python >=3.7,<3.10
    - numpy >=1.10.4
    - scikit-learn >=0.17.1
    - scipy >=0.17.0
    - pandas >=0.18.1

test:
  imports:
    - skrules
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-learn-contrib/skope-rules
  summary: Skope-rules is a Python machine learning module built on top of scikit-learn.
  license: BSD-3-Clause AND MIT
  license_file:
    - license.txt
    - COPYING

extra:
  recipe-maintainers:
    - rxm7706
